version: '2'
networks:
  lb_web:
    external: true
services:
  webhook:
    image: indiehosters/webhook
    environment:
    - LIBRESH_WEBHOOK_HOST=true
    volumes:
    - "/var/run/dbus:/var/run/dbus"
    - "/run/systemd:/run/systemd"
    - "/etc/systemd/system:/etc/systemd/system"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/data/domains:/data/domains"
    - "/opt/bin/:/opt/bin"
    - "./hooks.json:/hooks.json"
    networks:
    - lb_web
  discovery:
    image: jwilder/docker-gen
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./templates:/etc/docker-gen/templates"
    - ".:/hooks"
    command: "-watch /etc/docker-gen/templates/hooks.json.tmpl /hooks/hooks.json"
